### ISSUE TITLE
Skill Check Dialogs broken in dnd5e 0.96

### ISSUE THREAD

**Issue by crash1115** [trdischat/grouproll#10]
Trying to roll a skill check from the actor sheet gives the following error. Problem occurs with both PC's and NPCS:
![image](https://user-images.githubusercontent.com/41387713/93477515-1c971600-f8c9-11ea-9a8f-27ea8f3e3b21.png)

- Foundry 0.6.6
- dnd5e 0.96
- No other modules installed
- Reproduced in both in Chrome and the Foundry app

Module settings as follows:
![image](https://user-images.githubusercontent.com/41387713/93478074-a6df7a00-f8c9-11ea-840f-98f727038d3d.png)

**Comment by trdischat** [comment]
Try turning off the Average Rolls option.  Version 0.95 of the dnd5e system broke it, and I don't know that I am going to be able to fix it. New version 0.6.5 of the module disables the broken patch.  If I can figure out how to fix it, I may bring the feature back.  For now it is dead.

**Comment by crash1115** [comment]
👍 Disabling it did the trick, just wanted to make sure the issue was known. Thanks!
