### ISSUE TITLE
0.7.4: Breaks the "close" button on all windows

### ISSUE THREAD

**Issue by flamewave000** [trdischat/grouproll#12]
Not sure how it's breaking them, but I can't close any windows if this module is enabled on my 0.7.4 server.

**Comment by trdischat** [comment]
This was already fixed in version 0.6.6.  Have you updated yet?

**Comment by flamewave000** [comment]
Sorry, I just updated the server yesterday and did a module update then. I must have just missed your update. It's working now with v0.6.6, thanks!

**Comment by trdischat** [comment]
Great.  Glad to hear it.
