### ISSUE TITLE
Allowing selection of both passed/failed tokens?

### ISSUE THREAD

**Issue by gn0rr** [trdischat/grouproll#13]
Currently, pressing the Pass/Fail buttons also changes the Group Roll window contents. Thus, after pressing Pass, it appears to be no longer possible to press Fail to get the tokens that failed the prior check.

Idea: Change the behavior, so that the Pass/Fail sets will _only_ be updated/overwritten once the Roll button has been _pressed_ to perform a new roll. That would allow having access to both the failed/passed token sets for different actions.

**Comment by trdischat** [comment]
Thanks for the suggestion. Feature included in version 0.8.4.
