### ISSUE TITLE
pf2e rather than group check use victory points or follow the expert

### ISSUE THREAD

**Issue by krazmuze** [trdischat/grouproll#15]
pf2e does not have a group check rule, and unlike 5e can have critical success/failure on skill checks.   However the gamemastery guide has victory point rules for biased accumulated scoring and is good to use for group checks.  (critical success/failure is +/-10 over/under the DC while nat1/20 may not be a critical it just lowers/raises the success, but I would suspect you can just leverage the ruleset for that)

If result is for the group then use Accumulating Rolls

In cases where the PCs need to make checks to gain Victory Points, the amount they get for the degrees of success is up to you. The default scale detailed below works in most cases.
Critical Success The PCs gain 2 Victory Points.
Success The PCs gain 1 Victory Point.
Critical Failure The PCs lose 1 Victory Point. This means that the result of a PC’s check usually results in the party gaining either 1 or no Victory Points. However, specialized PCs have a solid chance of earning the party 2 Victory Points, and hare‑brained schemes have a fair chance of losing the PCs 1 Victory Point.

if the result is for individual (such as avoiding notice) rather than for the group (there are no group stealth rolls in pf2e) then use Follow the Expert 

Choose an ally attempting a recurring skill check while exploring, such as climbing, or performing a different exploration tactic that requires a skill check (like Avoiding Notice). The ally must be at least an expert in that skill and must be willing to provide assistance. While Following the Expert, you match their tactic or attempt similar skill checks. Thanks to your ally’s assistance, you can add your level as a proficiency bonus to the associated skill check, even if you’re untrained. Additionally, you gain a circumstance bonus to your skill check based on your ally’s proficiency (+2 for expert, +3 for master, and +4 for legendary).

**Comment by trdischat** [comment]
Sorry, but I don't play Pathfinder and really don't know the rules. This module was written for D&D 5e.  I only wrote an extension to the module to cover Pathfinder 2e because another user asked me to try.  Unfortunately, I don't have time to refine the module further to capture all the nuances of the pf2e rules.
