### ISSUE TITLE
Group passsive checks round up

### ISSUE THREAD

**Issue by ajclarke90** [trdischat/grouproll#16]
Full disclosure, I might be being an idiot!

Groups passive perceptions are: 11, 11, 13, 13, 14 = (62/5) = 12.4

Module shows Passive perception as 13, but 5e should always round down.

**Comment by trdischat** [comment]
Per the Player's Handbook, page 175: "If at least half the group succeeds, the whole group succeeds."  The module correctly sets the threshold number to the roll of the median of the party, not the average.
