### ISSUE TITLE
Cannot select PCs in PF2 2.5.3, FVTT 0.8.8

### ISSUE THREAD

**Issue by apoapostolov** [trdischat/grouproll#18]
![image](https://user-images.githubusercontent.com/4083812/123805793-0eb1ff00-d8f7-11eb-9602-df8a2efd9ea1.png)

**Comment by trdischat** [comment]
The tokens need to be owned by a player.  Check to see if you have assigned owner permissions to any tokens yet.  I just tried this with PF2e 2.6.0 and FVTT 0.8.8 and the button works fine for me.

**Comment by apoapostolov** [comment]
The tokens are assigned to players. I tested a little bit more and found that:
* If you select the tokens, and then open Group Roll - it works as expected.
* If you open Group Roll and it is empty, and then press PC button to get to add all players - it doesn't work. 
* If you open Group Roll and it is empty, and you select player tokens - it doesn't populate them

Also, the issue is only for Group Roll. Group Saves works as expected.

**Comment by apoapostolov** [comment]
Another issue I found, easy to repro:
* Open Group Roll (first icon) and try to add PCs, they will not be added. 
* Close Group Roll and try to open it again (first icon). The Group Roll dialog will NOT open. Still press the button 3-5 times.
* Open Group Save, it will be populated as if PC button was pressed. Still press the PC button again, and close Group Save
* All Group Roll dialogs that failed to open in step 2 will open. if you pressed the button 3-5 times, there will be 3-5 dialogs.

**Comment by trdischat** [comment]
I am not able to replicate any of the behaviors that you are witnessing.  Could you please confirm the exact versions of all software that you are running and that you have no other modules running besides Group Roll and libWrapper?  Do you see any error messages in the console when Group Roll malfunctions?

**Comment by apoapostolov** [comment]
Sorry, I should have started with the errors:

![image](https://user-images.githubusercontent.com/4083812/124362982-38459000-dc41-11eb-9583-77de282e9b6a.png)

TypeError: An error occurred while rendering GroupSkillCheckPF2E 132: Cannot read property 'undefined' of undefined
    at apps.js:526
    at Array.map (<anonymous>)
    at GroupSkillCheckPF2E.getTokenList (apps.js:515)
    at GroupSkillCheckPF2E.getData (apps.js:489)
    at GroupSkillCheckPF2E._render (foundry.js:2042)
    at L.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:465)
    at GroupSkillCheckPF2E.🎁Application.prototype._render#lib-wrapper (listeners.js:75)
    at GroupSkillCheckPF2E.🎁Application.prototype._render#0 (libWrapper-wrapper.js:160)
    at GroupSkillCheckPF2E.render (foundry.js:2004)
    at Object.onclick (apps.js:101)
(anonymous) @ foundry.js:2006
Promise.catch (async)
render @ foundry.js:2004
onclick @ apps.js:101
(anonymous) @ apps.js:181
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by apoapostolov** [comment]
The same error happens when Find the Culprit is used to only allow Group Roll + libwrapper.

I can zip and send you the world via wetransfer if this would be useful.

**Comment by trdischat** [comment]
Please send me a link to the world file.  I still can't create this error on my end.

**Comment by trdischat** [comment]
I am going to assume that this issue took care of itself.
