### ISSUE TITLE
BUG: 'Shift + Click' on 'Roll' doesn't display individual token rolls to chat

### ISSUE THREAD

**Issue by MarkeyMarke** [trdischat/grouproll#19]
**Environment:**
Group Rolls Checks and Saves v0.8.3
Foundry v0.8.9
Foundry VTT 5th Edition v1.4.3

**Expected Behavior:**
Output individual rolls into chat like shown in the README
![image](https://user-images.githubusercontent.com/32396474/134780550-2c8ba0cb-c639-403d-a7d5-3085b87ad98f.png)

**Actual Behavior:**
Individual rolls do not show in chat
https://user-images.githubusercontent.com/32396474/134780522-1e7e8cc2-1222-4052-bc7f-68c22fab50f3.mp4

**Comment by trdischat** [comment]
Click on the Group Roll bar in the chat to reveal the individual rolls.
