### ISSUE TITLE
Selected tokens no longer updated

### ISSUE THREAD

**Issue by Gnurrf** [trdischat/grouproll#21]
With current versions of Foundry (0.8.9) and 5E (1.5.3), the selection of tokens is no longer updated after a roll when pressing the Pass or Fail buttons. Only the list of displayed PCs/NPCs changes.

**Comment by trdischat** [comment]
That is not a bug, it's a feature that was requested in #13.  As explained in the README, starting with version 0.8.4 of the module, the "Pass" button toggles the display between all selected tokens or only those tokens with successful rolls, while the "Fail" button toggles the display between all selected tokens or only those tokens with failed rolls.  These buttons no longer change the token selection, they just filter the display.
