### ISSUE TITLE
V9, Group Roll buttons do not appear in the toolbar

### ISSUE THREAD

**Issue by apoapostolov** [trdischat/grouproll#22]
With the mod turned on, buttons do not appear in the toolbar.

Tested with no mods via Culprit, same issue. 

![image](https://user-images.githubusercontent.com/4083812/147893008-2d1a18d5-d0b1-4e22-b3c6-758236e22cd2.png)

**Comment by trdischat** [comment]
The module no longer supports Pathfinder.  See https://github.com/trdischat/grouproll#system-compatibility.
