### ISSUE TITLE
Support for PF2

### ISSUE THREAD

**Issue by apoapostolov** [trdischat/grouproll#3]
Please add support for PF2 or release a PF2 version that does the following

- support the PF2 skills + Perception (ability) + Class check/DC. In PF2, skills don't get to use any ability but you may want to keep this functionality because it is nice addition to PF2. 
- reames Passive skill values "Skill DC"
- renames Advantage Disadvantage into Fortune Misfortune
- similar to Fortune Misfortune, two cycled buttons to add +1, +2 or +4, or -1, -2, -4 to the roll.

**Comment by trdischat** [comment]
@apoapostolov, I agree that it would be great for grouproll to support other game systems.  I will take a look at how I put together grouproll and see if there is an easy way for it to be extended to other game systems.  That said, I only play dnd5e, I don't know pf2 or other rule systems, and I don't really have the time or inclination to learn them.  So it will probably require a pf2 enthusiast to make a mod to my module.

**Comment by trdischat** [comment]
Support for PF2e added.
