### ISSUE TITLE
Module is now v10 compatible only

### ISSUE THREAD

**Issue by kakaroto** [trdischat/grouproll#34]
Since https://github.com/trdischat/grouproll/commit/aa4372f2b9eaca15d512f7efdf2ef7016bda65e2, you've changed the module.json to use `id` field instead of `name` which makes it v10 compatible, but also means it's unusable in v9.
The module's minimum compatibility should be bumped from v0.7.2 to v10 for the 0.10.2+ releases of the module.
Also make sure to update the minimum in the Foundry admin interface (https://foundryvtt.com/packages/grouproll) otherwise any user on v9 trying to install it will have a module that fails to even appear in the module list.
Thanks.

**Comment by trdischat** [comment]
I made the changes to module.json in an attempt to be compatible with version 10.  Is there a way to make a module compatible with both versions 9 and 10?

**Comment by kakaroto** [comment]
You can include both v9 and v10 fields. Like id and name, system/dependencies and the relationships field, minCoreVersion/compatibleCoreaversion and compatibility object field, etc..

**Comment by trdischat** [comment]
Is `name` the only thing missing right now?

**Comment by kakaroto** [comment]
Based on that commit, I would assume so. I haven't reviewed the `module.json` or tested it, the issue was just reported to us and I passed it along to you.

**Comment by trdischat** [comment]
Thanks, @kakaroto.  I think I have this corrected in the latest release.
