### ISSUE TITLE
Icons for new damage/effect buttons not supported before version 10

### ISSUE THREAD

**Issue by trdischat** [trdischat/grouproll#35]
@cs96and, the Font Awesome icons used for the new damage/healing/effects buttons in the ability check template do not show up when the module is used in FVTT version 9.  It appears that these icons may have been added to FVTT in version 10.

**Comment by trdischat** [comment]
It looks like FVTT 9 uses version 5 of the free set of FA icons, while FVTT 10 uses version 6 of the pro set of FA icons.  So the majority of the FA icons available in FVTT 10 are not backwards compatible with FVTT 9.

**Comment by cs96and** [comment]
Sorry I never got time to look into this, thanks for fixing
