### ISSUE TITLE
Shift-click does not remove conditions

### ISSUE THREAD

**Issue by trdischat** [trdischat/grouproll#37]
@cs96and, you recently added to the Grouṗ Ability Check the option to apply a condition to a group of tokens.  Previously, shift-click would remove the condition.  With the latest release of FVTT 11, shift-click no longer removes the condition.  I will look into this when I find some time, unless you manage to fix it first.

**Comment by cs96and** [comment]
I've submitted a PR to fix this.  I also have an outstanding PR about renaming ability checks to saving throws

**Comment by trdischat** [comment]
PR merged.
