### ISSUE TITLE
Grouproll causes critical results not to color in green or red

### ISSUE THREAD

**Issue by apoapostolov** [trdischat/grouproll#4]
When Grouproll is turned on, critical results do not color the final result in green or red, despite the individual dice are colored properly. The results will render properly and results will turn green and red when the page is reloaded. 

While rolling:

![image](https://user-images.githubusercontent.com/4083812/79785312-57157a80-834c-11ea-8acf-067a52d7be5c.png)

After page is reloaded:

![image](https://user-images.githubusercontent.com/4083812/79785583-c25f4c80-834c-11ea-90b1-81de9a0f56da.png)

This may be conflict with other existing mods. These are installed:

- Actually Private Rolls
- Better Rolls for 5E
- Combat Utility Belt
- Deselection
- Dice Calcualtor
- Favourite Item Tab
- The Furnace
- Group Roll Check and Saves
- ImageDrop
- Gamemaster FOW
- Minor Quality of Life Improvements
- Modbox
- Pointer
- Grid Scale Menu
- Search Anywhere
- Skycons
- Tiles Browser
- Token Health
- Token Mold
- Torch
- Virtual Tabletop Asses - Iconizer
- Virtual Tabletop Asses - Party Overvirew
- Virtual Tabletop Asses - Tokenizer

**Comment by apoapostolov** [comment]
Confirmed not conflict. The issue is present when all but Grouproll are turned off.

**Comment by trdischat** [comment]
Fixed.
