### ISSUE TITLE
Group Saving Throw/Check Not Working (v11)

### ISSUE THREAD

**Issue by bookwyrm-val** [trdischat/grouproll#40]
Hello!

First of all, thank you for writing this module. It's been immensely helpful during my years of GMing! 

Since updating to v11, however, I seem to be having trouble specifically with the Group Saving Throw/Check button. Clicking on the menu button no longer brings up the dialogue. 

Find the Culprit seems to think that this is a conflict with DF Convenient Effects; disabling that mod allows the Group Saving Throw/Check button to work again.

These are the errors that come up when trying to use the button. 

![image](https://github.com/trdischat/grouproll/assets/66767292/16d4674b-9ffa-4ae7-b2d2-c9509c71814b)

**Comment by trdischat** [comment]
Should be fixed in release 0.11.2.
