### ISSUE TITLE
DnD 5e  3.0.0 Gamesystem is not compatible

### ISSUE THREAD

**Issue by thepting** [trdischat/grouproll#41]
Module appears to work fine for NPC/creatures, but when you select PCs they don't show up in the group-check window.

Foundry v11 b315, DND5e 3.0.1

**Comment by Cannonfodd** [comment]
Confirming that this is still an issue 
![Screenshot 2024-04-06 150605](https://github.com/trdischat/grouproll/assets/165810727/a4443ff7-f5e0-4974-9a3e-2b27ff89251c)

**Comment by Cannonfodd** [comment]
Seems to be linked into the lucky trait, none of my players are halflings or have taken the feat, I removed these and it now works for me. 
![image](https://github.com/trdischat/grouproll/assets/165810727/fded0aee-74ab-4ff7-8873-e9cd224b86ef)

**Comment by Commander-Fayne** [comment]
Where did you remove these traits from? Compendiums? And what exactly did you remove, items? Feats?

**Comment by trdischat** [comment]
Hopefully this is now fixed in the release for FVTT version 12. https://github.com/trdischat/grouproll/releases/tag/0.12.0
@thepting and @Cannonfodd, could you please confirm whether this now works for you?
