### ISSUE TITLE
Hover description for Group Roll field

### ISSUE THREAD

**Issue by apoapostolov** [trdischat/grouproll#6]
It is a bit unclear how Group Roll field value is chosen base don the rolled results. A hover over it that explains how the value is calculated/chosen would greatly improve the use of that value.

**Comment by trdischat** [comment]
Do you think that “Median roll for the group” would work?  Alternatively, “Minimum roll achieved by at least half of the group” is a bit more accurate and reflects the D&D 5e rule on which it was based.

**Comment by apoapostolov** [comment]
> Alternatively, “Minimum roll achieved by at least half of the group” is a bit more accurate and reflects the D&D 5e rule on which it was based.

This is the perfect hover information, IMO.

**Comment by trdischat** [comment]
Added to latest version.
