### ISSUE TITLE
Feature request: Add "Select Failed/Passed" buttons

### ISSUE THREAD

**Issue by Norc** [trdischat/grouproll#9]
In the chat output, I would love it if there were two buttons:

1. One that would automatically select all members of the group who passed
2. One that would automatically select all members of the group who failed

This would be *super* helpful for me for when I need to manually do something based on the roll results, for instance, giving health back to members of the group who passed a saving throw if MQoL accidentally did too much damage, etc.

Thanks!!

**Comment by trdischat** [comment]
Buttons added.
